---
server:
  contextPath: /aristoweb
---
spring:
  profiles: local,default
  logging.level.org.springframework.web: DEBUG
  logging.level.org.hibernate: ERROR
datasource:
  aristoweb:
    url: jdbc:mysql://localhost:3306/mainwebsite
    username: root
    password: arv@123
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
---
spring:
  profiles: prod
  logging.level.org.springframework.web: DEBUG
  logging.level.org.hibernate: ERROR
datasource:
  aristoweb:
    url: jdbc:mysql://localhost:54684/mainwebsite
    username: azure
    password: password
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect